# Generated by Django 6.0.2 on 2026-07-23 17:39

import django.core.validators
import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productvariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='design', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='design',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(help_text='JPEG, PNG, or WebP. Maximum 5 MB and 6000 × 6000 pixels.', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), shop.models.validate_design_image]),
        ),
        migrations.AlterField(
            model_name='design',
            name='in_stock',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
